build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"

publish:
    docker:
        repo: $$DOCKER_USERNAME/chronic_collector
        tag: latest
        username: $$DOCKER_USERNAME
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
